spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  exposed:
    generate-ddl: true


freitag.url: https://www.freitag.ch/en

logging.level.Exposed: DEBUG