CREATE TABLE IF NOT EXISTS products
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT   DATETIME     NOT NULL,
    MODIFIED_AT  DATETIME     NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_ID   VARCHAR(50)  NOT NULL
);
CREATE TABLE IF NOT EXISTS stocks
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT  DATETIME             NOT NULL,
    MODIFIED_AT DATETIME             NOT NULL,
    STOCK_ID    VARCHAR(30)          NOT NULL,
    COLOR       VARCHAR(50)          NOT NULL,
    IMAGE_URL   VARCHAR(300)         NOT NULL,
    "EXISTS"    BOOLEAN DEFAULT true NOT NULL,
    FK_PRODUCT_ID     BIGINT               NOT NULL,
    CONSTRAINT FK_PRODUCTSTOCKS_PRODUCT_ID FOREIGN KEY (FK_PRODUCT_ID) REFERENCES PRODUCTS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);